/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AcquisitionSystem: typeof import('./src/components/AcquisitionSystem/AcquisitionSystem.vue')['default']
    Alarm: typeof import('./src/components/AcquisitionSystem/Alarm.vue')['default']
    ConfigTable: typeof import('./src/components/AcquisitionSystem/ConfigTable.vue')['default']
    DeviceTable: typeof import('./src/components/AcquisitionSystem/DeviceTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Helper: typeof import('./src/components/AcquisitionSystem/Helper.vue')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    LandingPage: typeof import('./src/components/LandingPage.vue')['default']
    Line: typeof import('./src/components/charts/Line.vue')['default']
    MenuBar: typeof import('./src/components/AcquisitionSystem/MenuBar.vue')['default']
    ReadFile: typeof import('./src/components/AcquisitionSystem/ReadFile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowTime: typeof import('./src/components/AcquisitionSystem/ShowTime.vue')['default']
    SystemInformation: typeof import('./src/components/LandingPage/SystemInformation.vue')['default']
    Tools: typeof import('./src/components/AcquisitionSystem/Tools.vue')['default']
  }
}
